version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7878:7878"
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'
    environment:
      - DATABASE_URL=postgres://root:1234@postgres:5432/axum_postgres
      - SERVER_ADDRESS=0.0.0.0:7878
      - RUST_BACKTRACE=full
      - SQLX_OFFLINE=true
    networks:
      - app-network

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=axum_postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d axum_postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '1.4GB'
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
    